#!/bin/sh

# check if installed conf is different from repo

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=~/.config}

diff $XDG_CONFIG_HOME/nvim/init.lua ./nvim/init.lua

diff $XDG_CONFIG_HOME/nvim/lua/mappings.lua ./nvim/lua/mappings.lua
diff $XDG_CONFIG_HOME/nvim/lua/plugins.lua ./nvim/lua/plugins.lua

